name: CD
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build image and push to hub repository
        uses: docker/build-push-action@v1.1.0
        with:
          username: thalessantanna
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}, latest

