name: CD
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build image and push to hub repository
        uses: docker/build-push-action@v1.1.0
        with:
          username: thalessantanna
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thalessantanna/compare-coroutines-webflux
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update Kubernetes
        run: |
          cd k8s
          kustomize edit set image kotlinapp=thalessantanna/compare-coroutines-webflux:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit
        run: |
          git config --local user.email "deploy@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change tag image to program"

      - name: Push
        run: ad-m/github-push-action@master
